// Enhanced by course design review: see changelog at bottom of file.
// Re-run `node scripts/convert_calculus_material.mjs ...` after editing source material.

export const topicMeta = {
  id: "03_rolles_theorem_and_the_mean_value_theorem",
  title: "Rolle's Theorem and the Mean Value Theorem",
  hudDefault: "Arian University • Calculus 1",
  hudPrefix: "Arian • ",
  email: "",
};

const slidesData = [
  // ─────────────────────────────────────────────────────────────────────────────
  // TITLE + OBJECTIVES
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: "topic_title",
    type: "title",
    hud: "Arian University • Calculus 1",
    title: "Rolle's Theorem and the Mean Value Theorem",
    subtitle: "Arian University • Calculus 1",
    meta: "Topic 17 · Rolle & MVT · Session 4: Applications of Derivatives · ~20 min",
    notes:
      "Welcome back, Topic 16 found critical points where f′=0. Today we prove those horizontal tangents (and parallel secant tangents) are **guaranteed** when hypotheses hold. Teaser: Topic 18 uses these ideas for derivative tests.",
  },
  {
    id: "learning_objectives",
    type: "bullets",
    hud: "Arian University • Calculus 1",
    title: "Learning Objectives",
    lead: "By the end of this topic you will be able to:",
    blocks: [
      {
        id: "calculus1_roadmap",
        type: "course_path",
        layout: "topic_grid",
        currentId: "path_topic_17",
        items: [
          { id: "path_topic_01", number: 1, session: "S01 Preliminaries", label: "Review of Functions and Graphs", status: "completed" },
          { id: "path_topic_02", number: 2, session: "S01 Preliminaries", label: "Trigonometry and Graphing Review", status: "completed" },
          { id: "path_topic_03", number: 3, session: "S02 Limits and Continuity", label: "The Intuitive Concept of a Limit", status: "completed" },
          { id: "path_topic_04", number: 4, session: "S02 Limits and Continuity", label: "Limit Laws and Algebraic Evaluation", status: "completed" },
          { id: "path_topic_05", number: 5, session: "S02 Limits and Continuity", label: "One-Sided Limits and Limits at Infinity", status: "completed" },
          { id: "path_topic_06", number: 6, session: "S02 Limits and Continuity", label: "The Squeeze Theorem", status: "completed" },
          { id: "path_topic_07", number: 7, session: "S02 Limits and Continuity", label: "Continuity and the Intermediate Value Theorem", status: "completed" },
          { id: "path_topic_08", number: 8, session: "S03 Derivative Foundations", label: "Instantaneous Rate of Change", status: "completed" },
          { id: "path_topic_09", number: 9, session: "S03 Derivative Foundations", label: "Formal Definition of the Derivative", status: "completed" },
          { id: "path_topic_10", number: 10, session: "S03 Derivative Foundations", label: "Power Rule and Basic Properties", status: "completed" },
          { id: "path_topic_11", number: 11, session: "S03 Derivative Foundations", label: "Power, Constant Multiple, Sum, Difference", status: "completed" },
          { id: "path_topic_12", number: 12, session: "S03 Derivative Foundations", label: "The Product Rule", status: "completed" },
          { id: "path_topic_13", number: 13, session: "S03 Derivative Foundations", label: "The Chain Rule", status: "completed" },
          { id: "path_topic_14", number: 14, session: "S03 Derivative Foundations", label: "Implicit Differentiation", status: "completed" },
          { id: "path_topic_15", number: 15, session: "S04 Applications", label: "Related Rates", status: "completed" },
          { id: "path_topic_16", number: 16, session: "S04 Applications", label: "Critical Points and Extrema", note: "Previous", status: "completed", expanded: true },
          { id: "path_topic_17", number: 17, session: "S04 Applications", label: "Rolle's Theorem and the MVT", note: "Today", status: "current", expanded: true },
          { id: "path_topic_18", number: 18, session: "S04 Applications", label: "First and Second Derivative Tests", note: "Next", status: "next", expanded: true },
          { id: "path_topic_19", number: 19, session: "S04 Applications", label: "Optimization Problems", status: "upcoming" },
          { id: "path_topic_20", number: 20, session: "S04 Applications", label: "L'Hopital's Rule", status: "upcoming" },
          { id: "path_topic_21", number: 21, session: "S04 Applications", label: "Newton's Method and Linear Approximations", status: "upcoming" },
          { id: "path_topic_22", number: 22, session: "S05 Integration Foundations", label: "Antiderivatives and Indefinite Integrals", status: "upcoming" },
          { id: "path_topic_23", number: 23, session: "S05 Integration Foundations", label: "Approximating Area with Riemann Sums", status: "upcoming" },
          { id: "path_topic_24", number: 24, session: "S05 Integration Foundations", label: "The Definite Integral", status: "upcoming" },
          { id: "path_topic_25", number: 25, session: "S05 Integration Foundations", label: "The Fundamental Theorem of Calculus", status: "upcoming" },
          { id: "path_topic_26", number: 26, session: "S05 Integration Foundations", label: "Integration by Substitution", status: "upcoming" },
        ],
      },
    ],
    bullets: [
      { id: "objective_1", text: "State the hypotheses and conclusions of **Rolle's Theorem** and the **Mean Value Theorem**." },
      { id: "objective_2", text: "Verify hypotheses on a given interval before applying either theorem." },
      { id: "objective_3", text: "Find \\(c\\) guaranteed by the MVT on concrete intervals." },
      { id: "objective_4", text: "Use Rolle's / MVT to prove facts about roots and constant functions." },
      { id: "objective_5", text: "Interpret the geometry: horizontal tangent (Rolle) vs secant-parallel tangent (MVT)." },
    ],
    notes:
      "Roadmap: Topic 16 critical points done; Topic 17 today; Topic 18 derivative tests next. Callback: f′(c)=0 from Topic 16 is Rolle's conclusion.",
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // BLOCK 1: INTUITION + HYPOTHESES
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: "s01_why_horizontal_tangents_matter",
    type: "two-col",
    hud: "Arian University • Calculus 1",
    title: "Why Horizontal Tangents Matter",
    left: {
      paragraphs: [],
      bullets: [],
      blocks: [
        {
          id: "left_paragraph_1",
          type: "paragraph",
          text: "**Road-trip metaphor:** start and end at the same elevation on a smooth road. Somewhere between, you drive **perfectly level**, instantaneous slope zero. That is Rolle's idea in one picture.",
        },
        {
          id: "left_bullets",
          type: "nested_bullets",
          items: [
            { id: "b1", text: "Topic 16: we **hunt** for \\(f'(c)=0\\) on intervals." },
            { id: "b2", text: "Rolle's: if \\(f(a)=f(b)\\) plus smoothness, such a \\(c\\) **must exist**." },
          ],
        },
      ],
      lead: "Same start/end height on a smooth curve → a horizontal tangent somewhere inside.",
    },
    right: {
      paragraphs: [],
      bullets: [],
      blocks: [],
      media: {
        id: "right_rolle_road",
        kind: "calculus_widget",
        widget: "function_analysis",
        variant: "flex_plot",
        title: "f(x)=x²−4 on [−2,2]: equal endpoints",
        caption: "f(−2)=f(2)=0; dashed guide shows horizontal tangent at c=0.",
        formulaLabel: "f",
        plot: {
          plotType: "y_equals",
          formula: "f(x)=x^2-4",
          xDomain: [-2.6, 2.6],
          yDomain: [-5, 3],
          curves: [{ id: "f", expr: "x^2-4", stroke: "#2563eb", strokeWidth: 4 }],
          filledPoints: [
            { x: -2, y: 0 },
            { x: 2, y: 0 },
            { x: 0, y: -4 },
          ],
          hLines: [{ y: -4 }],
          vLines: [{ x: 0 }],
          tags: [{ text: "f'(0)=0", x: 0.35, y: -3.2 }],
        },
        params: { x: -1.4 },
        scriptedTimeline: [
          { t: 0, params: { x: -1.8 } },
          { t: 5, params: { x: -0.6 } },
          { t: 10, params: { x: 0 } },
        ],
      },
    },
    notes:
      "Road-trip metaphor on x²−4: equal endpoint heights, interior horizontal tangent at c=0. Bridge from Topic 16 critical-point search to Rolle's guarantee.",
  },
  {
    id: "s02_prerequisites_continuity_differentiability",
    type: "two-col",
    hud: "Arian University • Calculus 1",
    title: "Prerequisites: Continuity & Differentiability",
    left: {
      paragraphs: [],
      bullets: [],
      blocks: [
        {
          id: "left_misconception",
          type: "misconception_compare",
          title: "Rolle vs MVT: don't mix the extras",
          pairs: [
            {
              label: "Rolle's Theorem",
              text: "Needs **continuity** on \\([a,b]\\), **differentiability** on \\((a,b)\\), **and** \\(f(a)=f(b)\\). Conclusion: \\(\\exists c\\) with \\(f'(c)=0\\).",
            },
            {
              label: "Mean Value Theorem",
              text: "Needs **continuity** on \\([a,b]\\) and **differentiability** on \\((a,b)\\) only, **no** equal endpoints. Conclusion: \\(f'(c)=\\frac{f(b)-f(a)}{b-a}\\).",
            },
            {
              label: "Common slip",
              text: "Applying MVT to \\(|x-1|\\) on \\([0,2]\\), continuous but **not differentiable** at \\(x=1\\).",
            },
            {
              label: "Checklist",
              text: "Scan \\((a,b)\\) for **corners, cusps, vertical tangents** before either theorem.",
            },
          ],
        },
      ],
      lead: "Both need smoothness on the open interval; Rolle adds equal endpoint values.",
    },
    right: {
      paragraphs: [],
      bullets: [],
      blocks: [],
      media: {
        id: "right_hypotheses_gallery",
        kind: "calculus_widget",
        widget: "function_analysis",
        variant: "flex_plot",
        title: "Smooth vs broken hypotheses",
        caption: "Blue = OK; orange corner breaks differentiability.",
        formulaLabel: "f",
        plot: {
          plotType: "y_equals",
          formula: "f(x)=x^2",
          xDomain: [-2.2, 2.2],
          yDomain: [-0.5, 4.5],
          curves: [
            { id: "smooth", expr: "x^2", stroke: "#2563eb", strokeWidth: 4 },
            { id: "corner", expr: "abs(x)", stroke: "#c65a28", strokeWidth: 3, dashed: true },
          ],
          filledPoints: [{ x: 0, y: 0 }],
          tags: [
            { text: "x², diff. everywhere", x: -1.6, y: 3.2 },
            { text: "|x|, corner at 0", x: 0.5, y: 1.4 },
          ],
        },
        params: { x: 1.2 },
        scriptedTimeline: [
          { t: 0, params: { x: 1.5 } },
          { t: 6, params: { x: 0.3 } },
          { t: 12, params: { x: -0.8 } },
        ],
      },
    },
    notes:
      "misconception_compare contrasts Rolle extra hypothesis with MVT. flex_plot overlays parabola and |x| corner.",
  },
  {
    id: "s03_rolle_s_theorem",
    type: "two-col",
    hud: "Arian University • Calculus 1",
    title: "Rolle's Theorem",
    left: {
      paragraphs: [],
      bullets: [],
      blocks: [
        {
          id: "left_theorem",
          type: "theorem_box",
          title: "Rolle's Theorem",
          text: "If \\(f\\) is **continuous** on \\([a,b]\\), **differentiable** on \\((a,b)\\), and \\(f(a)=f(b)\\), then there exists \\(c\\in(a,b)\\) such that \\(f'(c)=0\\).",
        },
        {
          id: "left_geo",
          type: "paragraph",
          text: "**Geometry:** somewhere inside, the tangent is **horizontal**, the conclusion Topic 16 was hunting for.",
        },
      ],
      lead: "Equal endpoints + smoothness implies at least one horizontal tangent inside.",
    },
    right: {
      paragraphs: [],
      bullets: [],
      blocks: [],
      media: {
        id: "right_rolle_parabola",
        kind: "calculus_widget",
        widget: "function_analysis",
        variant: "flex_plot",
        title: "f(x)=x²−4x+3 on [1,3]",
        caption: "Endpoints on y=0; horizontal tangent guide at c=2.",
        formulaLabel: "f",
        plot: {
          plotType: "y_equals",
          formula: "f(x)=x^2-4*x+3",
          xDomain: [0.2, 3.8],
          yDomain: [-2.5, 4],
          curves: [{ id: "f", expr: "x^2-4*x+3", stroke: "#2563eb", strokeWidth: 4 }],
          filledPoints: [
            { x: 1, y: 0 },
            { x: 3, y: 0 },
            { x: 2, y: -1 },
          ],
          hLines: [{ y: -1 }],
          vLines: [{ x: 2 }],
          tags: [{ text: "c=2, f'(c)=0", x: 2.2, y: -0.4 }],
        },
        params: { x: 1.4 },
        scriptedTimeline: [
          { t: 0, params: { x: 1.2 } },
          { t: 5, params: { x: 2 } },
          { t: 10, params: { x: 2.6 } },
        ],
      },
    },
    notes: "theorem_box statement. flex_plot marks c=2 with horizontal guide.",
  },
  {
    id: "s04_example_1_applying_rolle_s_theorem",
    type: "two-col",
    hud: "Arian University • Calculus 1",
    title: "Example 1: Applying Rolle's Theorem",
    left: {
      paragraphs: [],
      bullets: [],
      blocks: [
        {
          id: "body_solution",
          type: "math_solution_steps",
          stepLayout: "flow",
          problem: "f(x)=x^2-4x+3\\text{ on }[1,3]\\text{, find }c",
          steps: [
            { id: "step_1", op: "=>", math: "\\text{Polynomial} \\Rightarrow \\text{cont. on }[1,3]", gap: "tight", say: "Continuity check." },
            { id: "step_2", math: "f'(x)=2x-4", gap: "tight", say: "Derivative on (1,3)." },
            { id: "step_3", math: "f(1)=0,\\ f(3)=0 \\Rightarrow f(1)=f(3)", gap: "tight", say: "Equal endpoints." },
            { id: "step_4", math: "2c-4=0 \\Rightarrow c=2", gap: "tight", say: "Solve f'(c)=0." },
            { id: "step_5", math: "c=2\\in(1,3)", gap: "loose", say: "Interior, Rolle verified." },
          ],
        },
      ],
      lead: "Verify each hypothesis, then solve f'(c)=0.",
    },
    right: {
      paragraphs: [],
      bullets: [],
      blocks: [],
      media: {
        id: "right_rolle_worked",
        kind: "calculus_widget",
        widget: "function_analysis",
        variant: "flex_plot",
        title: "Verify c=2 on the graph",
        caption: "Probe near x=2: tangent slope approaches 0.",
        formulaLabel: "f",
        plot: {
          plotType: "y_equals",
          formula: "f(x)=x^2-4*x+3",
          xDomain: [0.5, 3.5],
          yDomain: [-2, 3.5],
          probe: true,
          probeDefault: 2,
          curves: [{ id: "f", expr: "x^2-4*x+3", stroke: "#16a34a", strokeWidth: 4 }],
          vLines: [{ x: 2 }],
          hLines: [{ y: -1 }],
          filledPoints: [{ x: 2, y: -1 }],
        },
        params: { x: 1.6 },
        scriptedTimeline: [
          { t: 0, params: { x: 1.3 } },
          { t: 5, params: { x: 2 } },
          { t: 10, params: { x: 2.7 } },
        ],
      },
    },
    notes: "math_solution_steps replaces table. flex_plot confirms horizontal tangent at c=2.",
  },
  {
    id: "s05_challenge_optional_proof_of_rolle_s_theorem",
    type: "two-col",
    hud: "Arian University • Calculus 1",
    title: "[Challenge] Proof of Rolle's Theorem",
    left: {
      paragraphs: [],
      bullets: [],
      blocks: [
        {
          id: "left_steps",
          type: "proof_sketch",
          title: "Proof sketch (EVT + Fermat)",
          steps: [
            { id: "left_step_1", text: "By **EVT**, \\(f\\) attains max \\(M\\) and min \\(m\\) on \\([a,b]\\)." },
            { id: "left_step_2", text: "**Case 1:** \\(M=m\\) → constant → \\(f'(c)=0\\) for any interior \\(c\\)." },
            { id: "left_step_3", text: "**Case 2:** \\(M>m\\). Since \\(f(a)=f(b)\\), a non-endpoint extremum lies at \\(c\\in(a,b)\\)." },
            { id: "left_step_4", text: "**Fermat:** interior extremum ⇒ \\(f'(c)=0\\)." },
          ],
        },
      ],
      lead: "Optional, two cases, one interior horizontal tangent.",
    },
    right: {
      paragraphs: [],
      bullets: [],
      blocks: [],
      media: {
        id: "right_rolle_proof",
        kind: "calculus_widget",
        widget: "function_analysis",
        variant: "flex_plot",
        title: "Interior extremum, horizontal tangent",
        caption: "Non-constant case: max in the open interval.",
        formulaLabel: "f",
        plot: {
          plotType: "y_equals",
          formula: "f(x)=-(x-2)^2+3",
          xDomain: [0.2, 3.8],
          yDomain: [-1, 4],
          curves: [{ id: "f", expr: "-(x-2)^2+3", stroke: "#2563eb", strokeWidth: 4 }],
          filledPoints: [{ x: 2, y: 3 }],
          hLines: [{ y: 3 }],
          vLines: [{ x: 2 }],
        },
        params: { x: 1 },
      },
    },
    notes: "Light proof_sketch for optional viewers.",
  },
  {
    id: "s06_mean_value_theorem_mvt",
    type: "two-col",
    hud: "Arian University • Calculus 1",
    title: "Mean Value Theorem (MVT)",
    left: {
      paragraphs: [],
      bullets: [],
      blocks: [
        {
          id: "left_theorem",
          type: "theorem_box",
          title: "Mean Value Theorem",
          text: "If \\(f\\) is continuous on \\([a,b]\\) and differentiable on \\((a,b)\\), then there exists \\(c\\in(a,b)\\) with \\(\\displaystyle f'(c)=\\frac{f(b)-f(a)}{b-a}\\).",
        },
        {
          id: "left_geo",
          type: "paragraph",
          text: "**Geometry:** some interior tangent is **parallel** to the secant through the endpoints.",
        },
      ],
      lead: "Instantaneous slope equals average slope, Rolle without equal endpoints.",
    },
    right: {
      paragraphs: [],
      bullets: [],
      blocks: [],
      media: {
        id: "right_mvt_secant",
        kind: "calculus_widget",
        widget: "secant_tangent",
        title: "Secant parallel to tangent on f(x)=x²",
        caption: "Vary a and h until secant slope matches tangent slope (c≈1 on [0,2]).",
        formulaLabel: "f",
        params: { a: 0, h: 2 },
        scriptedTimeline: [
          { t: 0, params: { a: 0, h: 2 } },
          { t: 4, params: { a: 0.4, h: 1.4 } },
          { t: 8, params: { a: 0.8, h: 1 } },
          { t: 12, params: { a: 1, h: 0.35 } },
          { t: 16, params: { a: 1, h: 0.08 } },
        ],
      },
    },
    notes: "theorem_box MVT. secant_tangent timeline varies a and h for parallel slopes at c=1.",
  },
  {
    id: "s07_example_2_typical_mvt_problem",
    type: "two-col",
    hud: "Arian University • Calculus 1",
    title: "Example 2: Typical MVT Problem",
    left: {
      paragraphs: [],
      bullets: [],
      blocks: [
        {
          id: "body_solution",
          type: "math_solution_steps",
          stepLayout: "flow",
          splitAfter: 3,
          problem: "f(x)=x^3-2x\\text{ on }[-1,2]\\text{, find }c",
          steps: [
            { id: "step_1", op: "=>", math: "f(-1)=1,\\ f(2)=4", gap: "tight", say: "Endpoint values." },
            { id: "step_2", math: "\\frac{f(2)-f(-1)}{2-(-1)}=\\frac{3}{3}=1", gap: "tight", say: "Average slope." },
            { id: "step_3", math: "f'(x)=3x^2-2", gap: "tight", say: "Derivative." },
            { id: "step_4", math: "3c^2-2=1 \\Rightarrow c^2=1", gap: "tight", say: "Match f'(c) to average slope." },
            { id: "step_5", math: "c=\\pm 1;\\ c=-1\\text{ endpoint} \\Rightarrow c=1", gap: "loose", say: "Keep c in open interval." },
          ],
        },
      ],
      lead: "Average slope first, then f'(c) equals that slope.",
    },
    right: {
      paragraphs: [],
      bullets: [],
      blocks: [],
      media: {
        id: "right_mvt_cubic",
        kind: "calculus_widget",
        widget: "function_analysis",
        variant: "flex_plot",
        title: "f(x)=x³−2x: secant slope 1",
        caption: "Tangent at c=1 matches endpoint secant slope.",
        formulaLabel: "f",
        plot: {
          plotType: "y_equals",
          formula: "f(x)=x^3-2*x",
          xDomain: [-1.4, 2.4],
          yDomain: [-2, 5],
          curves: [{ id: "f", expr: "x^3-2*x", stroke: "#2563eb", strokeWidth: 4 }],
          filledPoints: [
            { x: -1, y: 1 },
            { x: 2, y: 4 },
            { x: 1, y: -1 },
          ],
          vLines: [{ x: 1 }],
          tags: [{ text: "c=1, f'(c)=1", x: 1.15, y: 1.5 }],
        },
        params: { x: 0.5 },
        scriptedTimeline: [
          { t: 0, params: { x: -0.5 } },
          { t: 6, params: { x: 1 } },
          { t: 12, params: { x: 1.6 } },
        ],
      },
    },
    notes: "Exam-style MVT with splitAfter solution. flex_plot marks c=1. Discard endpoint c=-1.",
  },
  {
    id: "s08_misconception_when_mvt_fails",
    type: "two-col",
    hud: "Arian University • Calculus 1",
    title: "Misconception: When MVT Fails",
    left: {
      paragraphs: [],
      bullets: [],
      blocks: [
        {
          id: "left_misconception",
          type: "misconception_compare",
          title: "Continuous is not enough",
          pairs: [
            {
              label: "Wrong",
              text: "\\(|x-1|\\) on \\([0,2]\\) has equal endpoints, so some \\(c\\) has \\(f'(c)=0\\).",
            },
            {
              label: "Right",
              text: "Corner at \\(x=1\\) ⇒ MVT **fails**. Where defined, \\(f'=\\pm1\\), never 0.",
            },
          ],
        },
        {
          id: "left_note",
          type: "paragraph",
          text: "Average slope is \\(0\\), yet no parallel tangent, hypotheses failed.",
        },
      ],
      lead: "One corner inside (a,b) breaks the MVT.",
    },
    right: {
      paragraphs: [],
      bullets: [],
      blocks: [],
      media: {
        id: "right_abs_corner",
        kind: "calculus_widget",
        widget: "function_analysis",
        variant: "flex_plot",
        title: "|x−1| on [0,2]",
        caption: "Horizontal secant, but no horizontal tangent.",
        formulaLabel: "f",
        plot: {
          plotType: "y_equals",
          formula: "f(x)=abs(x-1)",
          xDomain: [-0.2, 2.2],
          yDomain: [-0.3, 1.4],
          curves: [{ id: "f", expr: "abs(x-1)", stroke: "#c65a28", strokeWidth: 4 }],
          filledPoints: [
            { x: 0, y: 1 },
            { x: 2, y: 1 },
            { x: 1, y: 0 },
          ],
          hLines: [{ y: 1 }],
          openPoints: [{ x: 1, y: 0 }],
          tags: [{ text: "corner, f' undefined", x: 1.05, y: 0.55 }],
        },
        params: { x: 0.4 },
        scriptedTimeline: [
          { t: 0, params: { x: 0.2 } },
          { t: 6, params: { x: 0.7 } },
          { t: 12, params: { x: 1.3 } },
        ],
      },
    },
    notes: "misconception_compare corner trap. flex_plot |x-1| with secant y=1.",
  },
  {
    id: "s09_pause_try_find_the_point",
    type: "two-col",
    hud: "Arian University • Calculus 1",
    title: "Pause & Try: Find c",
    question: "Compute average slope, then solve f'(c) = average slope.",
    left: {
      paragraphs: [],
      bullets: [],
      blocks: [
        {
          id: "left_prompt",
          type: "nested_bullets",
          items: [
            { id: "p1", text: "\\(f(x)=x^2\\) on \\([0,2]\\), find MVT value \\(c\\)." },
            { id: "p2", text: "① Average slope  ② Set \\(f'(c)\\) equal  ③ Solve" },
          ],
        },
        {
          id: "left_pause",
          type: "pause_and_reveal",
          title: "Pause and work it",
          prompt: "Try before the next slide.",
          reveal: { text: "**c = 1**, average slope 2, \\(f'(c)=2c=2\\)." },
        },
      ],
      lead: "YouTube pause: find c where tangent slope matches the secant.",
    },
    right: {
      paragraphs: [],
      bullets: [],
      blocks: [],
      media: {
        id: "right_pause_secant",
        kind: "calculus_widget",
        widget: "secant_tangent",
        title: "Secant on [0,2]: find matching tangent",
        caption: "Full-interval secant; narrow h toward c=1.",
        formulaLabel: "f",
        params: { a: 0, h: 2 },
        scriptedTimeline: [
          { t: 0, params: { a: 0, h: 2 } },
          { t: 8, params: { a: 0.5, h: 1.2 } },
          { t: 16, params: { a: 1, h: 0.5 } },
        ],
      },
    },
    notes: "pause_and_reveal with answer. secant_tangent timeline hints toward c=1.",
  },
  {
    id: "s10_solution_pause_problem",
    type: "two-col",
    hud: "Arian University • Calculus 1",
    title: "Solution: Pause Problem",
    left: {
      paragraphs: [],
      bullets: [],
      blocks: [
        {
          id: "body_solution",
          type: "math_solution_steps",
          stepLayout: "flow",
          problem: "f(x)=x^2\\text{ on }[0,2]",
          steps: [
            { id: "step_1", op: "=>", math: "\\frac{f(2)-f(0)}{2-0}=\\frac{4}{2}=2", gap: "tight", say: "Average slope." },
            { id: "step_2", math: "f'(x)=2x", gap: "tight", say: "Derivative." },
            { id: "step_3", math: "2c=2 \\Rightarrow c=1", gap: "tight", say: "Match slopes." },
            { id: "step_4", math: "c=1\\in(0,2)", gap: "loose", say: "Valid interior point." },
          ],
        },
      ],
      lead: "c=1, tangent slope 2 matches secant slope 2.",
    },
    right: {
      paragraphs: [],
      bullets: [],
      blocks: [],
      media: {
        id: "right_pause_solution",
        kind: "calculus_widget",
        widget: "function_analysis",
        variant: "flex_plot",
        title: "Tangent parallel to secant at c=1",
        caption: "Probe at x=1: instantaneous slope equals average slope.",
        formulaLabel: "f",
        plot: {
          plotType: "y_equals",
          formula: "f(x)=x^2",
          xDomain: [-0.3, 2.3],
          yDomain: [-0.5, 4.5],
          probe: true,
          probeDefault: 1,
          curves: [{ id: "f", expr: "x^2", stroke: "#16a34a", strokeWidth: 4 }],
          filledPoints: [
            { x: 0, y: 0 },
            { x: 2, y: 4 },
            { x: 1, y: 1 },
          ],
          vLines: [{ x: 1 }],
        },
        params: { x: 1 },
      },
    },
    notes: "Reveal paired with s09. math_solution_steps + flex_plot at c=1.",
  },
  {
    id: "s11_example_3_edge_case_constant_function",
    type: "two-col",
    hud: "Arian University • Calculus 1",
    title: "Edge Case: Constant Function",
    left: {
      paragraphs: [],
      bullets: [],
      blocks: [
        {
          id: "body_solution",
          type: "math_solution_steps",
          stepLayout: "flow",
          problem: "f(x)=5\\text{ on }[2,7]",
          steps: [
            { id: "step_1", op: "=>", math: "\\text{Cont. and diff. on }[2,7]", gap: "tight", say: "Hypotheses OK." },
            { id: "step_2", math: "\\frac{f(7)-f(2)}{7-2}=0", gap: "tight", say: "Average slope zero." },
            { id: "step_3", math: "f'(x)=0\\ \\forall x", gap: "tight", say: "Every tangent horizontal." },
            { id: "step_4", math: "\\text{Any }c\\in(2,7)\\text{ works}", gap: "loose", say: "Non-unique c allowed." },
          ],
        },
      ],
      lead: "MVT guarantees existence, not uniqueness.",
    },
    right: {
      paragraphs: [],
      bullets: [],
      blocks: [],
      media: {
        id: "right_constant_mvt",
        kind: "calculus_widget",
        widget: "function_analysis",
        variant: "flex_plot",
        title: "f(x)=5: every tangent horizontal",
        caption: "Secant and every tangent have slope 0.",
        formulaLabel: "f",
        plot: {
          plotType: "y_equals",
          formula: "f(x)=5",
          xDomain: [1.5, 7.5],
          yDomain: [3, 7],
          curves: [{ id: "f", expr: "5", stroke: "#2563eb", strokeWidth: 4 }],
          hLines: [{ y: 5 }],
          filledPoints: [
            { x: 2, y: 5 },
            { x: 7, y: 5 },
          ],
        },
        params: { x: 4 },
      },
    },
    notes: "Degenerate MVT, infinitely many valid c values.",
  },
  {
    id: "s12_example_4_application_proving_only_one_root",
    type: "two-col",
    hud: "Arian University • Calculus 1",
    title: "Application: Exactly One Root",
    left: {
      paragraphs: [],
      bullets: [],
      blocks: [
        {
          id: "body_solution",
          type: "math_solution_steps",
          stepLayout: "flow",
          splitAfter: 2,
          problem: "f(x)=x^3+x-1\\text{ has exactly one real root}",
          steps: [
            { id: "step_1", op: "=>", math: "f(0)=-1<0,\\ f(1)=1>0", gap: "tight", say: "IVT, at least one root in (0,1)." },
            { id: "step_2", math: "\\text{Suppose roots }a<b", gap: "tight", say: "Contradiction setup." },
            { id: "step_3", math: "f(a)=f(b)=0 \\Rightarrow \\text{Rolle on }[a,b]", gap: "tight", say: "Equal endpoints." },
            { id: "step_4", math: "\\exists c:\\ f'(c)=0", gap: "tight", say: "Rolle conclusion." },
            { id: "step_5", math: "f'(x)=3x^2+1>0\\ \\forall x", gap: "loose", say: "Contradiction, one root only." },
          ],
        },
      ],
      lead: "IVT for existence, Rolle for uniqueness.",
    },
    right: {
      paragraphs: [],
      bullets: [],
      blocks: [],
      media: {
        id: "right_one_root",
        kind: "calculus_widget",
        widget: "function_analysis",
        variant: "flex_plot",
        title: "f and f': one crossing",
        caption: "f crosses once; f' never zero.",
        formulaLabel: "f",
        plot: {
          plotType: "y_equals",
          formula: "f(x)=x^3+x-1",
          xDomain: [-1.2, 1.2],
          yDomain: [-2, 2],
          curves: [
            { id: "f", expr: "x^3+x-1", stroke: "#2563eb", strokeWidth: 4 },
            { id: "fp", expr: "3*x^2+1", stroke: "#c65a28", strokeWidth: 3, dashed: true },
          ],
          hLines: [{ y: 0 }],
          tags: [{ text: "f'>0 always", x: -0.9, y: 1.4 }],
        },
        params: { x: 0.3 },
      },
    },
    notes: "IVT + Rolle application. flex_plot f and f'. Callback Topic 7.",
  },
  {
    id: "s13_challenge_optional_proving_a_constant_function",
    type: "two-col",
    hud: "Arian University • Calculus 1",
    title: "[Challenge] MVT Proof Sketch",
    left: {
      paragraphs: [],
      bullets: [],
      blocks: [
        {
          id: "left_steps",
          type: "proof_sketch",
          title: "f'=0 on an interval implies f is constant",
          steps: [
            { id: "left_step_1", text: "**Claim:** \\(f'(x)=0\\) on interval \\(I\\) ⇒ \\(f\\) constant on \\(I\\)." },
            { id: "left_step_2", text: "Pick \\(a<b\\) in \\(I\\). **MVT** on \\([a,b]\\): \\(\\exists c\\) with \\(f'(c)=\\frac{f(b)-f(a)}{b-a}\\)." },
            { id: "left_step_3", text: "Since \\(f'(c)=0\\), get \\(f(b)=f(a)\\). Arbitrary pair ⇒ **constant**." },
          ],
        },
      ],
      lead: "Optional MVT proof, compare any two points via one interior c.",
    },
    right: {
      paragraphs: [],
      bullets: [],
      blocks: [],
      media: {
        id: "right_constant_proof",
        kind: "calculus_widget",
        widget: "function_analysis",
        variant: "flex_plot",
        title: "Flat function: secant slope 0",
        caption: "f(x)=3 on [1,5]; every secant horizontal.",
        formulaLabel: "f",
        plot: {
          plotType: "y_equals",
          formula: "f(x)=3",
          xDomain: [0.5, 5.5],
          yDomain: [1, 5],
          curves: [{ id: "f", expr: "3", stroke: "#2563eb", strokeWidth: 4 }],
          filledPoints: [
            { x: 1, y: 3 },
            { x: 5, y: 3 },
          ],
          hLines: [{ y: 3 }],
        },
        params: { x: 3 },
      },
    },
    notes: "proof_sketch MVT implies constant function. Optional challenge slide.",
  },
  {
    id: "s14_interactive_lab_rolle_s_theorem_exploration",
    type: "visual_lab",
    hud: "Arian University • Calculus 1",
    title: "Lab: Rolle's Theorem on a Parabola",
    question: "When f(a)=f(b), where is f'(c)=0?",
    lead: "Three intervals on f(x)=x²−4x+3. Demo tab B on video.",
    labSiteNote: "Site: try all tabs, horizontal tangent stays at x=2 when endpoints match.",
    labExamples: [
      {
        id: "lab_narrow",
        label: "A · [1.2, 2.8]",
        formula: "f(x)=x^2-4x+3",
        steps: [
          { text: "Endpoints near the vertex." },
          { text: "Horizontal tangent still at c=2." },
        ],
        params: {
          plot: {
            xDomain: [0.8, 3.2],
            yDomain: [-1.5, 2.5],
            filledPoints: [{ x: 1.2, y: 0.16 }, { x: 2.8, y: 0.16 }],
            vLines: [{ x: 2 }],
            hLines: [{ y: -1 }],
          },
        },
      },
      {
        id: "lab_standard",
        label: "B · [1, 3]",
        formula: "f(1)=f(3)=0",
        steps: [
          { text: "Classic Rolle setup." },
          { text: "Confirm c=2 in (1,3)." },
        ],
        params: {
          plot: {
            xDomain: [0.2, 3.8],
            yDomain: [-2, 3],
            filledPoints: [{ x: 1, y: 0 }, { x: 3, y: 0 }, { x: 2, y: -1 }],
            vLines: [{ x: 2 }],
            hLines: [{ y: -1 }],
          },
        },
      },
      {
        id: "lab_wide",
        label: "C · [0, 4]",
        formula: "f(0)=f(4)=3",
        steps: [
          { text: "Wider interval, same endpoint height." },
          { text: "Same interior c=2." },
        ],
        params: {
          plot: {
            xDomain: [-0.5, 4.5],
            yDomain: [-2, 4],
            filledPoints: [{ x: 0, y: 3 }, { x: 4, y: 3 }],
            vLines: [{ x: 2 }],
            hLines: [{ y: -1 }],
          },
        },
      },
    ],
    media: {
      id: "lab_rolle_plot",
      kind: "calculus_widget",
      widget: "function_analysis",
      variant: "flex_plot",
      title: "Rolle lab",
      caption: "Green guides mark c where f'(c)=0.",
      formulaLabel: "f",
      plot: {
        plotType: "y_equals",
        formula: "f(x)=x^2-4*x+3",
        xDomain: [0.2, 3.8],
        yDomain: [-2, 3],
        probe: true,
        probeDefault: 2,
        curves: [{ id: "f", expr: "x^2-4*x+3", stroke: "#2563eb", strokeWidth: 4 }],
        vLines: [{ x: 2 }],
        hLines: [{ y: -1 }],
        filledPoints: [{ x: 1, y: 0 }, { x: 3, y: 0 }],
      },
      params: { x: 2 },
    },
    notes: "visual_lab with three interval tabs. Demo tab B ~30s on video.",
  },
  {
    id: "s15_interactive_lab_mvt_exploration",
    type: "visual_lab",
    hud: "Arian University • Calculus 1",
    title: "Lab: MVT, Match Secant and Tangent Slopes",
    question: "Drag a and h until secant slope equals tangent slope.",
    lead: "Three (a,h) presets on f(x)=x² for interval [0,2].",
    labSiteNote: "Site: switch tabs and read the slope readout.",
    labExamples: [
      {
        id: "lab_full_secant",
        label: "A · a=0, h=2",
        formula: "[0,2]\\text{ secant}",
        steps: [
          { text: "Full-interval secant, slope 2." },
          { text: "Tangent at a=1 also has slope 2." },
        ],
        params: { a: 0, h: 2 },
      },
      {
        id: "lab_mid",
        label: "B · a=0.5, h=1",
        formula: "narrower secant",
        steps: [
          { text: "Move base point right." },
          { text: "Secant slope approaches 2." },
        ],
        params: { a: 0.5, h: 1 },
      },
      {
        id: "lab_near_c",
        label: "C · a=1, h=0.1",
        formula: "near c=1",
        steps: [
          { text: "Small h at a=1." },
          { text: "Secant ≈ tangent, slopes match." },
        ],
        params: { a: 1, h: 0.1 },
      },
    ],
    media: {
      id: "lab_mvt_secant",
      kind: "calculus_widget",
      widget: "secant_tangent",
      title: "f(x)=x²: MVT geometry",
      caption: "Blue secant, green tangent, live slope readout.",
      formulaLabel: "f",
      params: { a: 0, h: 2 },
      scriptedTimeline: [
        { t: 0, params: { a: 0, h: 2 } },
        { t: 5, params: { a: 0.6, h: 1 } },
        { t: 10, params: { a: 1, h: 0.25 } },
        { t: 15, params: { a: 1, h: 0.06 } },
      ],
    },
    notes: "visual_lab secant_tangent tabs. Narrate tab B on video.",
  },
  {
    id: "s16_summary",
    type: "bullets",
    hud: "Arian University • Calculus 1",
    title: "Summary & Next Steps",
    lead: "Takeaways before Topic 18, First and Second Derivative Tests:",
    bullets: [
      { id: "takeaway_1", text: "**Rolle:** cont. + diff. + \\(f(a)=f(b)\\) ⇒ \\(\\exists c\\) with \\(f'(c)=0\\)." },
      { id: "takeaway_2", text: "**MVT:** cont. + diff. ⇒ \\(f'(c)=\\frac{f(b)-f(a)}{b-a}\\) for some \\(c\\)." },
      { id: "takeaway_3", text: "**Always** check differentiability on \\((a,b)\\), one corner breaks the theorem." },
      { id: "takeaway_4", text: "**Next:** Topic 18 classifies critical points with \\(f'\\) and \\(f''\\) sign tests." },
    ],
    blocks: [
      {
        id: "body_pause",
        type: "pause_and_reveal",
        title: "Exit check",
        prompt: "Quick recall before you go.",
        reveal: {
          text: "Rolle needs equal endpoints; MVT needs only smoothness. Both need **no corners** inside \\((a,b)\\).",
        },
      },
    ],
    notes: "Recap + Topic 18 teaser. pause_and_reveal exit check.",
  },
];

export default slidesData;

/*
 * COURSE DESIGN CHANGELOG. Topic 17 (v1 hand-enhanced, June 2026)
 *   - Welcome back + Topic 16 critical-points callback; path_topic_17 roadmap.
 *   - Removed source metadata; normal JS style.
 *   - theorem_box on s03 Rolle, s06 MVT; proof_sketch on s05 Rolle, s13 MVT constant.
 *   - misconception_compare on s02 (Rolle vs MVT) and s08 (corner trap).
 *   - math_solution_steps on s04, s07, s10, s11, s12 (flow + splitAfter).
 *   - flex_plot unique per slide; secant_tangent on s06, s09, s15 (vary a, h).
 *   - s14, s15 visual_lab with three example tabs each.
 *   - pause_and_reveal on s09 practice + s16 exit check.
 */